#!/bin/bash
PATH="$PWD/node_modules/.bin":$PATH
set -e

buildMicrobundle5() {
  set -x
  rm -rfv dist
  microbundle -i src/index.ts --tsconfig tsconfig.build.json --no-sourcemap --no-compress --target node -f esm -o dist
  name=$(cat package.json | jq -r '.name')
  cp -v README.md package.json dist
  cd dist
  mv index.d.ts "$name.d.ts"
  cat ../package.json | jq --arg name "$name" '
    .module = "./\($name).js" |
    .types = "./\($name).d.ts" |
    .exports.".".default = "./\($name).js"
  ' > package.json
  cd ..
  set +x
}

"$@"
